# Generated by Django 5.2 on 2026-03-21 18:07

import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(help_text='Digite um número com DDD. Ex:11 91234-5678', max_length=128, region='BR', verbose_name='Telefone')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('servico', models.CharField(choices=[('sites', 'Sites Profissionais'), ('ecommerce', 'E-commerce Completo'), ('chatbots', 'Chatbots Inteligentes'), ('api', 'APIs & Integrações'), ('ia', 'Inteligência Artificial'), ('sistemas', 'Sistemas Web Sob Medida'), ('outros', 'Outros / Não sei')], max_length=50, verbose_name='Serviço de interesse')),
                ('mensagem', models.TextField(default='', verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('lido', 'Lido'), ('respondido', 'Respondido'), ('arquivado', 'Arquivado')], db_index=True, default='novo', max_length=20, verbose_name='Status')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('data_envio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de envio')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_envio'],
            },
        ),
    ]
