# Generated by Django 5.2 on 2026-03-24 01:56

import user.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='default/project_img.jpg', help_text='Formato de arquivo: jpg, jpeg ou png.', null=True, upload_to='portfolios/', validators=[user.validators.validate_image_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Portifólio',
                'verbose_name_plural': 'Portifólios',
                'ordering': ['-created_at'],
            },
        ),
    ]
